---
- name: Install Python Software Properties
  apt: name=python-software-properties state=present update_cache=yes

- name: Add Nginx Repository
  apt_repository: repo='ppa:nginx/stable'

- name: Update apt-cache
  apt: update_cache=yes

- name: Install Nignx
  apt: name=nginx state=present

- name: Print nginx version
  command: nginx -v

- name: Add nginx-ansible config to sites-enabled
  template: src=nginx-ansible.conf dest=/etc/nginx/sites-enabled/nginx-ansible
  notify: restart nginx



#- debug: msg="This Nginx Version is {{ nginx_version.stdout }}"
